
#!/bin/bash

# ============================================================
#  SUTRA - System for Unified Threat & Risk Analysis
#  Deployment Script for Ubuntu 22.04+
#  Usage: sudo bash sutra-deploy.sh
#  Place the SUTRA zip file in the same directory as this script.
# ============================================================

set -e

# ──────────────────────────────────────────────
# 0. ROOT CHECK
# ──────────────────────────────────────────────
if [[ $EUID -ne 0 ]]; then
  echo "❌ This script must be run as root or with sudo"
  exit 1
fi

# ──────────────────────────────────────────────
# 1. CONFIGURATION — EDIT THESE BEFORE RUNNING
# ──────────────────────────────────────────────
DOMAIN="sutra.subhajjisuhas.me"
EMAIL="suhas4341@gmail.com"
GEMINI_API_KEY="your-key"
MAPBOX_TOKEN="pk.eyJ1..."
APP_DIR="/opt/sutra"
NODE_VERSION="20"

# ──────────────────────────────────────────────
# 2. VALIDATE CONFIG
# ──────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════╗"
echo "║    SUTRA Deployment — Pre-flight Check   ║"
echo "╚══════════════════════════════════════════╝"

if [[ -z "$DOMAIN" ]]; then
  echo "❌ DOMAIN is not set."; exit 1
fi
if [[ "$GEMINI_API_KEY" == "your-key" ]]; then
  echo "❌ Please replace GEMINI_API_KEY with your actual key."; exit 1
fi
if [[ -z "$EMAIL" ]]; then
  echo "❌ EMAIL is not set."; exit 1
fi

# ──────────────────────────────────────────────
# 3. FIND ZIP IN WORKING DIRECTORY
# ──────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ZIP_FILE=$(find "$SCRIPT_DIR" -maxdepth 1 -name "*.zip" | head -1)

if [[ -z "$ZIP_FILE" ]]; then
  echo "❌ No .zip file found in $SCRIPT_DIR"
  echo "   Place the SUTRA zip file in the same directory as this script and re-run."
  exit 1
fi

echo "✅ Found zip     : $ZIP_FILE"
echo "✅ Domain        : $DOMAIN"
echo "✅ Install dir   : $APP_DIR"
echo ""

# ──────────────────────────────────────────────
# 4. SYSTEM DEPENDENCIES
# ──────────────────────────────────────────────
echo "▶ [1/7] Installing system dependencies..."
apt-get update -qq
apt-get install -y -qq \
  curl git nginx certbot python3-certbot-nginx \
  unzip build-essential ca-certificates gnupg
echo "✅ System dependencies installed."

# ──────────────────────────────────────────────
# 5. NODE.JS + PM2
# ──────────────────────────────────────────────
echo "▶ [2/7] Installing Node.js $NODE_VERSION..."
if ! command -v node &> /dev/null; then
  curl -fsSL https://deb.nodesource.com/setup_${NODE_VERSION}.x | bash -
  apt-get install -y nodejs
else
  echo "   Node.js already installed: $(node --version)"
fi
npm install -g pm2 --silent
echo "✅ Node.js $(node --version) and PM2 ready."

# ──────────────────────────────────────────────
# 6. EXTRACT ZIP → APP_DIR
# ──────────────────────────────────────────────
echo "▶ [3/7] Extracting SUTRA from zip..."

mkdir -p "$APP_DIR"

# Extract to a temp folder first, then copy into APP_DIR
TEMP_DIR=$(mktemp -d)
unzip -q "$ZIP_FILE" -d "$TEMP_DIR"

# Case 1: flat zip (SUTRA default) — package.json directly in root
# Case 2: wrapped zip — package.json inside a single subfolder
if [[ -f "$TEMP_DIR/package.json" ]]; then
  cp -r "$TEMP_DIR"/. "$APP_DIR/"
else
  EXTRACTED_ROOT=$(find "$TEMP_DIR" -mindepth 1 -maxdepth 1 -type d | head -1)
  if [[ -n "$EXTRACTED_ROOT" && -f "$EXTRACTED_ROOT/package.json" ]]; then
    cp -r "$EXTRACTED_ROOT"/. "$APP_DIR/"
  else
    echo "❌ Could not locate package.json inside the zip. Is this the correct SUTRA zip?"
    rm -rf "$TEMP_DIR"
    exit 1
  fi
fi

rm -rf "$TEMP_DIR"
echo "✅ Extracted to $APP_DIR"

# ──────────────────────────────────────────────
# 7. WRITE .env
# ──────────────────────────────────────────────
cat > "$APP_DIR/.env" <<EOF
# SUTRA Environment — generated by sutra-deploy.sh on $(date)
GEMINI_API_KEY=${GEMINI_API_KEY}
VITE_MAPBOX_ACCESS_TOKEN=${MAPBOX_TOKEN}
APP_URL=https://${DOMAIN}
NODE_ENV=production
PORT=3000
EOF
chmod 600 "$APP_DIR/.env"
echo "✅ .env written."

# ──────────────────────────────────────────────
# 8. BUILD
# ──────────────────────────────────────────────
echo "▶ [4/7] Installing dependencies and building..."
cd "$APP_DIR"
npm install --silent
npm run build
echo "✅ Build complete."

# ──────────────────────────────────────────────
# 9. PM2
# ──────────────────────────────────────────────
echo "▶ [5/7] Configuring PM2..."

mkdir -p /var/log/sutra

cat > "$APP_DIR/ecosystem.config.cjs" <<EOF
module.exports = {
  apps: [
    {
      name: 'sutra',
      script: 'server.ts',
      interpreter: 'node',
      interpreter_args: '--import tsx/esm',
      cwd: '${APP_DIR}',
      env_file: '${APP_DIR}/.env',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      error_file: '/var/log/sutra/error.log',
      out_file: '/var/log/sutra/out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
  ],
};
EOF

pm2 delete sutra 2>/dev/null || true
pm2 start "$APP_DIR/ecosystem.config.cjs"
pm2 save
pm2 startup systemd -u root --hp /root | tail -1 | bash 2>/dev/null || true
echo "✅ PM2 running on port 3000."

# ──────────────────────────────────────────────
# 10. NGINX
# ──────────────────────────────────────────────
echo "▶ [6/7] Configuring Nginx..."

cat > /etc/nginx/sites-available/sutra <<EOF
server {
    listen 80;
    server_name ${DOMAIN};

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://\$host\$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name ${DOMAIN};

    ssl_certificate     /etc/letsencrypt/live/${DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${DOMAIN}/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;

    location / {
        proxy_pass         http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header   Host              \$host;
        proxy_set_header   X-Real-IP         \$remote_addr;
        proxy_set_header   X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto \$scheme;
        proxy_set_header   Upgrade           \$http_upgrade;
        proxy_set_header   Connection        "upgrade";
        proxy_read_timeout 120s;
    }
}
EOF

ln -sf /etc/nginx/sites-available/sutra /etc/nginx/sites-enabled/sutra
rm -f /etc/nginx/sites-enabled/default
mkdir -p /var/www/certbot
nginx -t
systemctl enable nginx
systemctl start nginx
systemctl reload nginx
echo "✅ Nginx configured."

# ──────────────────────────────────────────────
# 11. SSL
# ──────────────────────────────────────────────
echo "▶ [7/7] Obtaining SSL certificate..."

certbot --nginx \
  -d "$DOMAIN" \
  --non-interactive \
  --agree-tos \
  -m "$EMAIL" \
  --redirect

# Auto-renew cron
(crontab -l 2>/dev/null; echo "0 0,12 * * * certbot renew --quiet && systemctl reload nginx") | crontab -

systemctl restart nginx
echo "✅ SSL certificate installed with auto-renewal."

# ──────────────────────────────────────────────
# 12. FIREWALL
# ──────────────────────────────────────────────
if command -v ufw &> /dev/null; then
  ufw allow 22/tcp
  ufw allow 80/tcp
  ufw allow 443/tcp
  ufw --force enable
  echo "✅ UFW firewall configured."
fi

# ──────────────────────────────────────────────
# DONE
# ──────────────────────────────────────────────
echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║          ✅  SUTRA Deployment Complete!              ║"
echo "╠══════════════════════════════════════════════════════╣"
echo "║  App URL  : https://${DOMAIN}                        "
echo "║  App Dir  : ${APP_DIR}                               "
echo "║  Logs     : /var/log/sutra/                          "
echo "╚══════════════════════════════════════════════════════╝"
echo ""
echo "  View logs   →  pm2 logs sutra"
echo "  Restart     →  pm2 restart sutra"
echo "  Nginx check →  nginx -t && systemctl status nginx"
echo ""
Content is user-generated and unverified.
SUTRA Deployment Script for Ubuntu 22.04 – Complete Setup Guide | Claude
